[package]
name = "matplotlib-pyo3"
version = "0.1.2"
authors = [
    "Elias Kuthe <elias.kuthe@tu-dortmund.de>",
    "Till Hartmann <till.hartmann@udo.edu>"
]
edition = "2021"

[dependencies]
pyo3 = "0.15"
numpy = "0.15"
ndarray = "0.15"
anyhow = "1.0"
