[package]
name = "matplotlib-pyo3"
version = "0.1.1"
authors = [
    "Elias Kuthe <elias.kuthe@tu-dortmund.de>",
    "Till Hartmann <till.hartmann@udo.edu>"
]
edition = "2018"

[dependencies]
pyo3 = "0.13"
numpy = "0.13"
anyhow = "1.0"
ndarray = "0.14"
